"""add delivery fields to job cards

Revision ID: 4a01adcaafb1
Revises: c4ded97d9d4c
Create Date: 2026-07-19 11:01:37.842042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a01adcaafb1'
down_revision: Union[str, Sequence[str], None] = 'c4ded97d9d4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_cards', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.add_column('job_cards', sa.Column('delivered_to', sa.String(length=100), nullable=True))
    op.add_column('job_cards', sa.Column('delivery_remarks', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_cards', 'delivery_remarks')
    op.drop_column('job_cards', 'delivered_to')
    op.drop_column('job_cards', 'delivered_at')
    # ### end Alembic commands ###
