"""create master options table

Revision ID: 4bb68dbf4ac3
Revises: bdf93017e2f6
Create Date: 2026-07-18 18:44:03.392003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb68dbf4ac3'
down_revision: Union[str, Sequence[str], None] = 'bdf93017e2f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_type', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('option_type', 'code', name='uq_master_option_type_code')
    )
    op.create_index(op.f('ix_master_options_id'), 'master_options', ['id'], unique=False)
    op.create_index(op.f('ix_master_options_option_type'), 'master_options', ['option_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_options_option_type'), table_name='master_options')
    op.drop_index(op.f('ix_master_options_id'), table_name='master_options')
    op.drop_table('master_options')
    # ### end Alembic commands ###
