"""create spare parts and stock transactions

Revision ID: 675e322b39e5
Revises: 7a1095eed650
Create Date: 2026-07-19 07:14:26.365282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675e322b39e5'
down_revision: Union[str, Sequence[str], None] = '7a1095eed650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spare_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_code', sa.String(length=20), nullable=False),
    sa.Column('part_name', sa.String(length=150), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('minimum_stock', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spare_parts_id'), 'spare_parts', ['id'], unique=False)
    op.create_index(op.f('ix_spare_parts_part_code'), 'spare_parts', ['part_code'], unique=True)
    op.create_table('stock_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spare_part_id', sa.Integer(), nullable=False),
    sa.Column('job_card_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_cards.id'], ),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transactions_id'), 'stock_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_stock_transactions_job_card_id'), 'stock_transactions', ['job_card_id'], unique=False)
    op.create_index(op.f('ix_stock_transactions_spare_part_id'), 'stock_transactions', ['spare_part_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_transactions_spare_part_id'), table_name='stock_transactions')
    op.drop_index(op.f('ix_stock_transactions_job_card_id'), table_name='stock_transactions')
    op.drop_index(op.f('ix_stock_transactions_id'), table_name='stock_transactions')
    op.drop_table('stock_transactions')
    op.drop_index(op.f('ix_spare_parts_part_code'), table_name='spare_parts')
    op.drop_index(op.f('ix_spare_parts_id'), table_name='spare_parts')
    op.drop_table('spare_parts')
    # ### end Alembic commands ###
