"""create workflow transitions table

Revision ID: 7a1095eed650
Revises: b58d5a4bc3a9
Create Date: 2026-07-19 05:02:17.375341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a1095eed650'
down_revision: Union[str, Sequence[str], None] = 'b58d5a4bc3a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=False),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_transitions_from_status'), 'workflow_transitions', ['from_status'], unique=False)
    op.create_index(op.f('ix_workflow_transitions_id'), 'workflow_transitions', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_transitions_to_status'), 'workflow_transitions', ['to_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_transitions_to_status'), table_name='workflow_transitions')
    op.drop_index(op.f('ix_workflow_transitions_id'), table_name='workflow_transitions')
    op.drop_index(op.f('ix_workflow_transitions_from_status'), table_name='workflow_transitions')
    op.drop_table('workflow_transitions')
    # ### end Alembic commands ###
