"""create job cards table

Revision ID: b58d5a4bc3a9
Revises: b3f6f52157ba
Create Date: 2026-07-19 02:54:49.633680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b58d5a4bc3a9'
down_revision: Union[str, Sequence[str], None] = 'b3f6f52157ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_code', sa.String(length=20), nullable=False),
    sa.Column('service_request_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('repair_notes', sa.Text(), nullable=True),
    sa.Column('labour_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_request_id'], ['service_requests.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_cards_id'), 'job_cards', ['id'], unique=False)
    op.create_index(op.f('ix_job_cards_job_code'), 'job_cards', ['job_code'], unique=True)
    op.create_index(op.f('ix_job_cards_service_request_id'), 'job_cards', ['service_request_id'], unique=True)
    op.create_index(op.f('ix_job_cards_technician_id'), 'job_cards', ['technician_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_cards_technician_id'), table_name='job_cards')
    op.drop_index(op.f('ix_job_cards_service_request_id'), table_name='job_cards')
    op.drop_index(op.f('ix_job_cards_job_code'), table_name='job_cards')
    op.drop_index(op.f('ix_job_cards_id'), table_name='job_cards')
    op.drop_table('job_cards')
    # ### end Alembic commands ###
