"""create service requests table

Revision ID: bdf93017e2f6
Revises: ea034987ddbc
Create Date: 2026-07-18 18:25:56.821866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bdf93017e2f6'
down_revision: Union[str, Sequence[str], None] = 'ea034987ddbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_code', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_product_id', sa.Integer(), nullable=False),
    sa.Column('complaint_category', sa.String(length=100), nullable=False),
    sa.Column('complaint_description', sa.Text(), nullable=False),
    sa.Column('received_accessories', sa.String(length=255), nullable=True),
    sa.Column('product_condition', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('estimated_delivery', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['customer_product_id'], ['customer_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_code')
    )
    op.create_index(op.f('ix_service_requests_id'), 'service_requests', ['id'], unique=False)
    op.alter_column('customer_products', 'warranty_status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('customer_products', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_customer_products_customer_id'), 'customer_products', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_products_serial_number'), 'customer_products', ['serial_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_products_serial_number'), table_name='customer_products')
    op.drop_index(op.f('ix_customer_products_customer_id'), table_name='customer_products')
    op.alter_column('customer_products', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('customer_products', 'warranty_status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('ix_service_requests_id'), table_name='service_requests')
    op.drop_table('service_requests')
    # ### end Alembic commands ###
