"""create technicians table

Revision ID: c902cb2e8801
Revises: 4bb68dbf4ac3
Create Date: 2026-07-18 19:34:03.740992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c902cb2e8801'
down_revision: Union[str, Sequence[str], None] = '4bb68dbf4ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technician_code', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('specialization', sa.String(length=150), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('availability_status', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_technicians_id'), 'technicians', ['id'], unique=False)
    op.create_index(op.f('ix_technicians_technician_code'), 'technicians', ['technician_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technicians_technician_code'), table_name='technicians')
    op.drop_index(op.f('ix_technicians_id'), table_name='technicians')
    op.drop_table('technicians')
    # ### end Alembic commands ###
